import { getTournaments } from "services/getService";
import About from "../components/main/About";
import MainTitle from "../components/main/MainTitle";
import Tournaments from "../components/main/Tournaments/index";

export const metadata = {
  title: "CrazyGoat",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getTournaments();

  return (
    <main className="w-full">
      <MainTitle />
      <img src="/space_rabbit_v2.svg" alt="" className="w-12 h-12" />
      <About />
      <Tournaments products={products} />
    </main>
  );
}
