import { getTournaments } from "services/getService";
import About from "../components/main/About";
import MainTitle from "../components/main/MainTitle";
import Tournaments from "../components/main/Tournaments/index";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getTournaments();

  if (!products?.data?.tournoments?.length) return null;

  return (
    <main className="w-full">
      <MainTitle />
      <About />
      <Tournaments products={products} />
    </main>
  );
}
